### ISSUE TITLE
Call hierarchy support

### ISSUE THREAD

**Issue by SPGoding** [SPGoding/datapack-language-server#298]
Proposed documentation: https://github.com/microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.callHierarchy.proposed.md

# Prepare
Return the corresponding `CallHierarchyItem` of the selected function/function tag.

# Incoming calls
A function can be called from:
- [x] A function. We can get this from the said function's `ref`. (#316)
- [x] A function tag. We should maintain a map of `TagInfo` in order to get this. (#315)

A function tag can be called from:
- [x] A function. We can get this from the said function tag's `ref`. (#316)
- [x] Another function tag. We should maintain a map of `TagInfo` in order to get this. (#315)

# Outgoing calls
A function can call:
- [x] A function. We can get this from all functions' `ref` and compare if the `uri` of that cache position is the expected one.
- [x] A function tag. We can get this from all function tags' `ref` and compare if the `uri` of that cache position is the expected one. 

A function tag can call:
- [x] A function. We should maintain a map of `TagInfo` in order to get this. (#315)
- [x] Another function tag. We should maintain a map of `TagInfo` in order to get this. (#315)
