### ISSUE TITLE
Improve semantic coloring

### ISSUE THREAD

**Issue by SPGoding** [SPGoding/datapack-language-server#307]
See https://github.com/microsoft/vscode-languageserver-node/blob/master/testbed/server/src/server.ts#L476 for LSP reference.

# Checklist
- [x] Use our own set of tokens to best describe the syntax of `mcfunction` files: #308.
- [x] Use the semantic tokens builder provided by LSP module: #310.
- [x] Support `edit` request: #312.
